spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ukemeny}
    username: ${DB_USERNAME:ukemeny}
    password: ${DB_PASSWORD:ukemeny}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
