spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ukemeny
    username: ukemeny
    password: ukemeny
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
